Resources for the ASM+ACM tutorial
GoogleCloudPlatform/anthos-config-management-samples pull request #40
Opened 2022-04-07 12:32 UTC by mathieu-benoit

2022-04-07 17:03 UTC, ckim328 commented
Thanks for getting this ready @mathieu-benoit! 
I ran this output under the `Initialize PoCo & ConfigSync (RootSync + RepoSync) repos`  'Checks'  in the walkthrough, 
```
gcloud alpha anthos config sync repo list
```
and im running into this output 
```
christineskim@cloudshell:~ (ck-acm-asm)$ gcloud alpha anthos config sync repo list
ERROR: Error describing the membership NAME:: ERROR: (gcloud.container.fleet.memberships.describe) INVALID_ARGUMENT: Malformed name: 'NAME:'
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: Resource name violates RFC 3986
    field: 'NAME:'

getting 2 RepoSync and RootSync from asm-acm-tutorial
SOURCE: https://github.com/GoogleCloudPlatform/anthos-config-management-samples//asm-acm-tutorial/root-sync/init@asm-acm-tutorial
TOTAL: 1
SYNCED: 1
PENDING: 0
ERROR: 0
STALLED: 0
RECONCILING: 0

SOURCE: https://github.com/mathieu-benoit/asm-acm-tutorial//online-boutique/init@main:HEAD
TOTAL: 1
SYNCED: 1
PENDING: 0
ERROR: 0
STALLED: 0
RECONCILING: 0
```

2022-04-07 18:23 UTC, mathieu-benoit commented
Hey @ckim328, thanks for the feedback, yep that's actually a current issue within Cloud Shell (b/227517057). I don't know in which version of gcloud the fix will be included. As a temporary workaround, you could run this command before: `gcloud config set accessibility/screen_reader false`. Feel free to ping me if that's not resolving your issue.

2022-04-07 20:05 UTC, ckim328 commented
ran through the steps, looks good! just wondering are you planning on having the README.md hyperlinked to the tutorial? i think it would be helpful to have something similar to the walkthrough step that you created in this PR's description. (ie doesn't have to be super in depth, but an overview of what the PR does)

2022-04-07 21:33 UTC, mathieu-benoit commented
Hey @ckim328, yep I was thinking first to document the steps of the tests in the `README.md` but then I landed to add this placeholder in that file: `FIXME - link to the tutorial once published.`. The latter will avoid any duplication/maintenance. Are you ok with that or any other suggestion for this?

2022-04-08 13:06 UTC, ckim328 commented
I think even providing a brief overview of the products/goals of the walkthrough
something like "This demo found here (link to tutorial) will be showing Policy Controller and Config Sync to add more security for an ASM setup with Online Boutique." or along those lines
(no need to put in gcloud cmds, i agree to reduce effort in maintenance)

2022-04-12 14:08 UTC, ckim328 approved these changes
looks stellar! I'll make a follow PR once this is merged for region tags, awesome job 😎

2022-04-13 17:24 UTC, NimJay approved these changes
I've left some preliminary comments about these changes.
Still running through the steps you listed.
It's taking me a while.

2022-04-13 17:25 UTC, NimJay requested changes
Sorry. Approved by accident. Changing to "request changes".

2022-04-14 12:03 UTC, mathieu-benoit commented on asm-acm-tutorial/README.md
> +3. `enforce-sidecar-injection`
I wasn't but yeah I agree with you, even if the name of the folders are kind of explicit, it's better to have a sentence per item for both clarification and consistency. Thanks for the suggestion, I just committed the fix for that.

2022-04-14 18:31 UTC, mathieu-benoit commented on asm-acm-tutorial/online-boutique/authorization-policies/kustomization.yaml
> +components:
I would say that's 2 different concepts:
- `components`: in this current `kustomization.yaml` file I have 3 ways to aggregate resources or patches: `components`, `resources` or directly in-line patches
- `patches`: could be in a `kustomization.yaml` file or in a `component` file, and then you could use your option to patch files: `patch`, `patchesJson6902`, `patchesStrategicMerge` or `replacements` for example.
Does that help and does that answer your questions?

2022-04-20 18:27 UTC, NimJay approved these changes
@mathieu-benoit, thanks for giving me a better understanding of this pull-request (via call).

When I first reviewed this and ran:
```
gcloud alpha anthos config sync repo describe \
    --managed-resources all \
    --sync-name repo-sync \
    --sync-namespace onlineboutique
getting 1 RepoSync and RootSync from asm-acm-tutorial
```
I got the following error: 
```
getting 1 RepoSync and RootSync from asm-acm-tutorial
ERROR: gcloud crashed (KeyError): 'resourceStatuses'

If you would like to report this issue, please run the following command:
  gcloud feedback

To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
```

It looks like I am no longer getting the above error. :)
We will be end-to-end testing the tutorial anyway (plus Christine was able to successfully execute the steps), so I will go ahead and approve this pull-request.

I am also happy with the set of Gatekeeper Policies (i.e., `constraints.gatekeeper`) we're enforcing in this change.

2022-04-20 18:39 UTC, merged